version: "3"

services:
    builder:
        build: .
        image: code.lab10.io:4567/graz/10-minerva/minerva-android-v2:builder
        volumes:
            - ./:/var/app
        networks:
          - minerva

networks:
    minerva:
        driver: bridge
